disableKinds = ["taxonomy", "term"]
baseURL = "https://vishwasunil.github.io/voice-to-people/"
languageCode = "en-us"
title = "Voice to People"
canonifyURLs = true
relativeURLs = true
[params]
    description = "Indiaâ€™s high-leverage independent news platform. Historical truths and forgotten narratives."
    author = "Vishwas Sunil"
    logo = "images/logo.png"
    logo = "static/images/icons/back.svg"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "History"
    url = "/categories/history"
    weight = 3
